name: Node.js CI

on:
  merge_group:
    branches:
      - main
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    permissions:
      contents: read

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: latest

      - run: npm ci
      - run: npm run build
      - run: npm run lint
      - run: npm test

  fix:
    permissions:
      contents: write

    needs: test

    if: failure() && github.event_name != 'merge_group' && github.actor != 'github-actions[bot]' && github.actor != 'nektos/act'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref || github.ref }}
      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: latest

      - run: |
          npm install
          git add .
      - id: commit-lockfile
        uses: qoomon/actions--create-commit@v1
        with:
          message: |
            📌 npm install --fix-lockfile

            [dependabot skip]
          skip-empty: true

      - run: |
          npx ts-autofix --project tsconfig.json
          git add .
          - id: commit-ts-autofix
            uses: qoomon/actions--create-commit@v1
            with:
            message: |
              💚 ts-autofix --project tsconfig.json

              [dependabot skip]
            skip-empty: true

      - run: |
          npm run format
          git add .
          - id: commit-format
            uses: qoomon/actions--create-commit@v1
            with:
            message: |
              🎨 npm run format

              [dependabot skip]
            skip-empty: true

      - run: |
          npm run lint:fix
          git add .
          - id: commit-lint
            uses: qoomon/actions--create-commit@v1
            with:
              message: |
                🚨 npm run lint:fix

                [dependabot skip]
              skip-empty: true

          - if: steps.commit-lockfile.outputs.commit || steps.commit-ts-autofix.outputs.commit || steps.commit-format.outputs.commit || steps.commit-lint.outputs.commit
            run: git push
